apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pihole
  name: pihole-udp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: dns-udp
    nodePort: 30482
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: client-udp
    nodePort: 31077
    port: 67
    protocol: UDP
    targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
