apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: network-services
    metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: pihole
  name: pihole-tcp
  namespace: home
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.178.254
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: pihole-https
    port: 443
    protocol: TCP
    targetPort: pihole-https
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
