apiVersion: v1
kind: ConfigMap
metadata:
  namespace: pihole
  name: config
data:
  config: |
    address-pools:
    - name: pihole
      protocol: layer2
      addresses:
      - 192.168.50.80-192.168.50.90