---
dnsmasq:
  customDnsEntries:
    - address=/nas/192.168.50.22
  customCnameEntries:
    - cname=grafana.k8s.home,grafana.192.168.50.208.nip.io

persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.50.21
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.50.21
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  
resources:
limits:
  cpu: '200m'
  memory: '512Mi'
requests:
  cpu: '300m'
  memory: '256Mi'

adminPassword: MyN3tworkP1Clu$ter
 