{{ if .Values.ftl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-ftl
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pihole-FTL.conf: |
  {{- range $key, $value := .Values.ftl }}
    {{ $key }}={{ $value }}
  {{- end }}
{{ end }}
