{{ if not (empty .Values.localDns.dnsRecords) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-customList
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  custom.list: |
  {{- range .Values.localDns.dnsRecords }}
    {{ . }}
  {{- end }}
{{ end }}
