{{ if .Values.domains }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-domains
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  domains.sh: |
    #!/usr/bin/env bash
    # shellcheck disable=SC1090

    # List of pihole commands to configure / reconfigure permit and deny lists
  {{- if eq .Values.domains.alwaysNuke true }}
    pihole -w --nuke --noreload 
    pihole -b --nuke --noreload 
    pihole --white-wild --nuke --noreload 
    pihole --wild --nuke --noreload 
    pihole --white-regex --nuke --noreload 
    pihole --regex --nuke --noreload 
    pihole restartdns reload
    sleep 5
  {{- end }}
  {{- if .Values.domains.permit }}
    {{- range .Values.domains.permit }}
    pihole -w --noreload {{ . }} --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
  {{- if .Values.domains.deny }}
    {{- range .Values.domains.deny }}
    pihole -b --noreload {{ . }} --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
  {{- if .Values.domains.permitWildcard }}
    {{- range .Values.domains.permitWildcard }}
    pihole --white-wild --noreload {{ . }} --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
  {{- if .Values.domains.denyWildcard }}
    {{- range .Values.domains.denyWildcard }}
    pihole --wild --noreload {{ . }} --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
  {{- if .Values.domains.permitRegex }}
    {{- range .Values.domains.permitRegex }}
    pihole --white-regex --noreload '{{ . }}' --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
  {{- if .Values.domains.denyRegex }}
    {{- range .Values.domains.denyRegex }}
    pihole --regex --noreload '{{ . }}' --comment "Added by pihole Helm chart"
    {{- end }}
  {{- end }}
    pihole restartdns reload
    # End of list
{{ end }}
