apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-tcp
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
      # HTTP(S)
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https

      # DNS
    - port: 53
      targetPort: dns
      protocol: TCP
      name: dns
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp

      # DHCP
    {{- if .Values.dhcpSupportEnabled.ipv4 }}
    - port: 67
      targetPort: dhcp-udp
      protocol: UDP
      name: dhcp-udp
    {{- end }}
    {{- if .Values.dhcpSupportEnabled.ipv6 }}
    - port: 547
      targetPort: dhcpv6-udp
      protocol: UDP
      name: dhcpv6-udp
    {{- end }}
  selector:
    app: {{ template "pihole.name" . }}
    release: {{ .Release.Name }}
