name: Deploy To Pi Cluster

on:
  push:
    branches:
      - "master"

jobs:
  deploy-via-kubectl:
    name: Deploy to Pi Cluster
    runs-on: self-hosted
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    
    - name:  step check if release exists
      run: | 
           STATUS=$(helm status pihole -n pihole || echo "NOT_FOUND")
           NOT_FOUND="release: not found"
           if [[ "$STATUS" == *"NOT_FOUND"* ]]; then
               echo "deployed=false" >> $GITHUB_ENV
           fi
    # Run deployment manifesto
    - name: Check out repository code
      uses: actions/checkout@v3
        
    - name: if pihole helm release does not exist then install
      if: env.deployed 
      run: helm install --namespace pihole -f ./charts/pihole/values.yaml pihole ./charts/pihole
   
    - name: if release exists then upgrade 
      if: false == env.deployed
      run: helm upgrade pihole -f ./charts/pihole/values.yaml --namespace pihole ./charts/pihole

