name: Deploy To Pi Cluster

on:
  push:
    branches:
      - "master"

jobs:
  deploy-via-kubectl:
    name: Deploy to Pi Cluster
    runs-on: self-hosted
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Run deployment manifesto
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: 'Deploy'
      run: helm upgrade --namespace pihole -f ./charts/pihole/values.yaml pi-hole ./charts/pihole
        