name: Deploy To Pi Cluster

on:
  push:
    branches:
      - "master"

jobs:
  deploy-via-kubectl:
    name: Deploy to Pi Cluster
    runs-on: self-hosted
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # Run deployment manifesto
    - name: 'Deploy'
      run: helm update -f ./charts/vaules.yaml pihole ./pihole
        # release: 'exacerbated-gecko'
        # namespace: 'pihole'
        # chart: 'pihole'
        # value-files: 
        #   "./charts/vaules.yaml"
        