name: prepare-release
on:
  push:
    branches:
      - release-*

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate documentation
        id: generate-documentation
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(documentation): Update documentation'